name: PHP Composer

on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  fix: # make sure the action works on a clean machine without building
    permissions:
      pull-requests: write
      contents: write
      
    runs-on: ubuntu-latest
    defaults:
       run:
         working-directory: ./
    steps:
      - uses: actions/checkout@v3
        with:
            persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of the personal access token.
            fetch-depth: 0  # otherwise, there would be errors pushing refs to the destination repository.
             
      - uses: actions/checkout@v3
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ./
             
      - uses: codeeshop-oc/php-cs-fix-merge@1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          username: codeeshop-oc
          email: github-action[bot]@users.noreply.github.com
          temp_branch_name: php-cs-fix
          master_branch_name: main
          commit_message: Automated Bot Deployment
          pull_title: Automated Bot Deployment
          pull_body: Update PHP CS Fix Files
          assignee: codeeshop-oc
          reviewer: codeeshop-oc
